version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: apps/game-backend/Dockerfile
    env_file: ./apps/game-backend/.env
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
